var shuffleSequence = seq("intro", 
                          "intro_sep", 
                          sepWith("within_intro_sep", "practice"), 
                          "practice_sep", 
                          sepWith("sep", 
                            rshuffle(startsWith("rc_condition"), 
                                    startsWith("gen_condition"),
                            )), //
                          "send_results",
                         "debrief"); 
var practiceItemTypes = ["practice"];

// default settings
var manualSendResults = true;


var defaults = [
    "Separator", {
        // transfer: 1000,
        transfer: "keypress",
        hideProgressBar: true,
        normalMessage: "", 
        errorMessage: "Daha hızlı yanıtlayınız.",
        transfer: 600
    },
    "DashedAcceptabilityJudgment", {
        hideProgressBar: true,
        timeout: 5000,
        
        as: [["p","İYİ (P'ye basınız)"], ["q","KÖTÜ (Q'ya basınız)"]],
        q: "Bu cümle kulağınıza nasıl geliyor?",
        
        mode: "speeded acceptability",
        display: "in place",
        wordTime: 400,
        wordPauseTime: 100,
        instructions: " ",

        showNumbers: true,
        hasCorrect: false,
        autoFirstChar: false,
        showNumbers: false
    },
    "Question", {
        hideProgressBar: true,
        timeout: 10000,

        as: [["p","İYİ (P'ye basınız)"], ["q","KÖTÜ (Q'ya basınız)"]],
        instructions: "Bu cümle kulağınıza nasıl geliyor?",
        hasCorrect: false,
        randomOrder: false,
        autoFirstChar: false,
        showNumbers: false
    },
    "Message", {
        hideProgressBar: false
    },
    "Form", {
        hideProgressBar: true,
        continueOnReturn: true,
        saveReactionTime: true,
        continueMessage: "Devam etmek için buraya tıklayınız.",
        obligatoryCheckboxErrorGenerator: function (field) { return "Bu alanı doldurmanız gerekmektedir." },
        obligatoryErrorGenerator: function (field) { return "Bu alanı doldurmanız gerekmektedir."; },
        obligatoryRadioErrorGenerator: function (field) { return "Seçeneklerden birini seçiniz."; }
        
    }
];

function modifyRunningOrder(ro) {
        for (var i = 0; i < ro.length; ++i) {
            if ( (i != 0) && (i % 40 == 0)) {
                // Passing 'true' as the third argument casues the results from this controller to be omitted from the results file. 
                // (Though in fact, the Message controller does not add any results in any case.)
                ro[i].push(new DynamicElement(
                    "Message",
                    { html: "<p>Kısa bir ara. Bir sonraki cümleye geçmek için boşluk tuşuna basınız.</p>", transfer: "keypress"}, //, transfer: 1000 
                    true
                ));
            }
        }
        return ro;
    }


var items = [
    ["send_results", "__SendResults__", { }],


    ["sep", "Separator", {
        hideProgressBar: false,
        transfer: "keypress",
        normalMessage: "Bir sonraki cümleye geçmek için boşluk tuşuna basınız.",
        errorMessage:  "Bir sonraki cümleye geçmek için boşluk tuşuna basınız."}],

    ["intro_sep", "Separator", {
        hideProgressBar: false,
        transfer: "keypress",
        normalMessage: "Alıştırma kısmına başlamak için boşluk tuşuna basınız. (Unutmayın: Cümleye ve anlamına dair sezgilerinizle ilgileniyoruz, dolayısıyla hızlıca yanıt veriniz.)",
        errorMessage: "Alıştırma kısmına başlamak için boşluk tuşuna basınız. (Unutmayın: Cümleye ve anlamına dair sezgilerinizle ilgileniyoruz, dolayısıyla hızlıca yanıt veriniz.)" }],

    ["within_intro_sep", "Separator", {
        hideProgressBar: false,
        transfer: "keypress",
        normalMessage: "Bir sonraki cümleye geçmek için boşluk tuşuna basınız.",
        errorMessage: "Lütfen soruları okurken biraz daha dikkatli olalım."}],

    ["practice_sep", "Separator", {
        hideProgressBar: false,
        transfer: "keypress",
        normalMessage: "Deneye başlamak için boşluk tuşuna basınız.",
        errorMessage: "Lütfen soruları okurken biraz daha dikkatli olalım." }],

    ["intro", "Form", {
        html: { include: "intro1.html" },
        obligatoryCheckboxErrorGenerator: function (field) { return "Devam etmeden önce çalışmaya katılmayı kabul etmelisiniz."; }
    } ],
    
    ["intro", "Form", {
        html: { include: "intro2.html" },
        validators: {
            age: function (s) { if (s.match(/^\d+$/)) return true; else return "Yaşınızı sayı olarak giriniz."; },
        }
    } ],

    ["intro", "Form", {
        html: { include: "intro3.html" } } ],

    ["intro", "Form", {
        html: { include: "intro4.html" } } ],

    ["intro", "Form", {
        html: { include: "intro5.html" } } ],
    
    ["debrief", "Message", {
        html: { include: "debrief.html" },
                transfer: 3000  }],
["practice", "DashedAcceptabilityJudgment", {s: "Bu kısım deneye ve sunum yöntemine alışmanız için bulunmaktadır." , hasCorrect: 0 } ],
["practice", "DashedAcceptabilityJudgment", {s: "Bu cümle öncekinden daha uzun bir cümle. Okuması biraz daha zor olsa da sunum şekli aslında aynı. Şimdi deneydekilere benzer cümleler görelim." , hasCorrect: 0 } ],
["practice", "DashedAcceptabilityJudgment", {s: "Öğrencinin asistanı gelince ders çok güzel anlattı." , hasCorrect: 1 } ],
["practice", "DashedAcceptabilityJudgment", {s: "Utku'nun kızı yürüyene kadar bir sürü oyuncak alınmıştı." , hasCorrect: 0 } ],
["practice", "DashedAcceptabilityJudgment", {s: "Kimsenin çocuğu ağlamayınca yeni yazılan kitap kimseye okumadı." , hasCorrect: 1 } ],
["practice", "DashedAcceptabilityJudgment", { s: "Tuğrul hiç kimseye bir şey demeden bir buçuk saattir okulun bahçesine bekliyor." , hasCorrect: 1 } ],
["practice", "DashedAcceptabilityJudgment", { s: "Jülide hiçbir evin bahçesine yeşil sivri biber fidelerini dün sabah dikmemiş." , hasCorrect: 0 } ],
["practice", "DashedAcceptabilityJudgment", { s: "Simitçi ve midyeci zabıtanın geldiğini görünce koşarak uzaklaştı." , hasCorrect: 0 } ],
["practice", "DashedAcceptabilityJudgment", { s: "Futbolcu hakemin seyircilerin taşkınlık yapmasını gerekçe gösterince sinirlendiler." , hasCorrect: 1 } ],
    
["practice", Message, {consentRequired: false, transfer: "keypress",
                     html: ["div",
                           ["p", "Elinizin ısındığını umuyorum. Hazır olduğunuzu hissettiğinizde 'boşluk' tuşuna basarak ilerleyiniz."],
                           ["p", "NOT: Vereceğiniz cevaplar üzerine çok düşünmeyin! Tamamlayacağınız deneyde 'doğru' ya da 'yanlış' cevap bulunmamaktadır. Deney boyunca deneye odaklanmanız gerekmektedir."]
                           ["p", "Katılımınız için çok teşekkürler!"],
                           ]}],
    

[["rc_condition_a", 101], "DashedAcceptabilityJudgment", {s: "Dövdükleri çocuk okula yorgun argın geldiler."}],
[["rc_condition_b", 101], "DashedAcceptabilityJudgment", {s: "Dövdükleri çocuk okula yorgun argın geldi."}],
[["rc_condition_c", 101], "DashedAcceptabilityJudgment", {s: "Dövdüğü çocuk okula yorgun argın geldiler."}],
[["rc_condition_d", 101], "DashedAcceptabilityJudgment", {s: "Dövdüğü çocuk okula yorgun argın geldi."}],
[["rc_condition_a", 102], "DashedAcceptabilityJudgment", {s: "Tuttukları aşçı mutfakta sürekli zıpladılar."}],
[["rc_condition_b", 102], "DashedAcceptabilityJudgment", {s: "Tuttukları aşçı mutfakta sürekli zıpladı."}],
[["rc_condition_c", 102], "DashedAcceptabilityJudgment", {s: "Tuttuğu aşçı mutfakta sürekli zıpladılar."}],
[["rc_condition_d", 102], "DashedAcceptabilityJudgment", {s: "Tuttuğu aşçı mutfakta sürekli zıpladı."}],
[["rc_condition_a", 103], "DashedAcceptabilityJudgment", {s: "Tanıdıkları müdür sınıfta birden bayıldılar."}],
[["rc_condition_b", 103], "DashedAcceptabilityJudgment", {s: "Tanıdıkları müdür sınıfta birden bayıldı."}],
[["rc_condition_c", 103], "DashedAcceptabilityJudgment", {s: "Tanıdığı müdür sınıfta birden bayıldılar."}],
[["rc_condition_d", 103], "DashedAcceptabilityJudgment", {s: "Tanıdığı müdür sınıfta birden bayıldı."}],
[["rc_condition_a", 104], "DashedAcceptabilityJudgment", {s: "Gördükleri marangoz atölyeden hızla uzaklaştılar."}],
[["rc_condition_b", 104], "DashedAcceptabilityJudgment", {s: "Gördükleri marangoz atölyeden hızla uzaklaştı."}],
[["rc_condition_c", 104], "DashedAcceptabilityJudgment", {s: "Gördüğü marangoz atölyeden hızla uzaklaştılar."}],
[["rc_condition_d", 104], "DashedAcceptabilityJudgment", {s: "Gördüğü marangoz atölyeden hızla uzaklaştı."}],
[["rc_condition_a", 105], "DashedAcceptabilityJudgment", {s: "Azarladıkları emlakçı aniden küstahça güldüler."}],
[["rc_condition_b", 105], "DashedAcceptabilityJudgment", {s: "Azarladıkları emlakçı aniden küstahça güldü."}],
[["rc_condition_c", 105], "DashedAcceptabilityJudgment", {s: "Azarladığı emlakçı aniden küstahça güldüler."}],
[["rc_condition_d", 105], "DashedAcceptabilityJudgment", {s: "Azarladığı emlakçı aniden küstahça güldü."}],
[["rc_condition_a", 106], "DashedAcceptabilityJudgment", {s: "Reddetikleri akademisyen sabaha kadar ağladılar."}],
[["rc_condition_b", 106], "DashedAcceptabilityJudgment", {s: "Reddetikleri akademisyen sabaha kadar ağladı."}],
[["rc_condition_c", 106], "DashedAcceptabilityJudgment", {s: "Reddettiği akademisyen sabaha kadar ağladılar."}],
[["rc_condition_d", 106], "DashedAcceptabilityJudgment", {s: "Reddettiği akademisyen sabaha kadar ağladı."}],
[["rc_condition_a", 107], "DashedAcceptabilityJudgment", {s: "Beklettikleri araştırmacı gün boyunca sıkıldılar."}],
[["rc_condition_b", 107], "DashedAcceptabilityJudgment", {s: "Beklettikleri araştırmacı gün boyunca sıkıldı."}],
[["rc_condition_c", 107], "DashedAcceptabilityJudgment", {s: "Beklettiği araştırmacı gün boyunca sıkıldılar."}],
[["rc_condition_d", 107], "DashedAcceptabilityJudgment", {s: "Beklettiği araştırmacı gün boyunca sıkıldı."}],
[["rc_condition_a", 108], "DashedAcceptabilityJudgment", {s: "Baktıkları hasta günden güne zayıfladılar."}],
[["rc_condition_b", 108], "DashedAcceptabilityJudgment", {s: "Baktıkları hasta günden güne zayıfladı."}],
[["rc_condition_c", 108], "DashedAcceptabilityJudgment", {s: "Baktığı hasta günden güne zayıfladılar."}],
[["rc_condition_d", 108], "DashedAcceptabilityJudgment", {s: "Baktığı hasta günden güne zayıfladı."}],
[["rc_condition_a", 109], "DashedAcceptabilityJudgment", {s: "Yordukları oyuncu onikiden önce uyudular."}],
[["rc_condition_b", 109], "DashedAcceptabilityJudgment", {s: "Yordukları oyuncu onikiden önce uyudu."}],
[["rc_condition_c", 109], "DashedAcceptabilityJudgment", {s: "Yorduğu oyuncu onikiden önce uyudular."}],
[["rc_condition_d", 109], "DashedAcceptabilityJudgment", {s: "Yorduğu oyuncu onikiden önce uyudu."}],
[["rc_condition_a", 110], "DashedAcceptabilityJudgment", {s: "Çalıştırdıkları hizmetçi yorgun argın yattılar."}],
[["rc_condition_b", 110], "DashedAcceptabilityJudgment", {s: "Çalıştırdıkları hizmetçi yorgun argın yattı."}],
[["rc_condition_c", 110], "DashedAcceptabilityJudgment", {s: "Çalıştırdığı hizmetçi yorgun argın yattılar."}],
[["rc_condition_d", 110], "DashedAcceptabilityJudgment", {s: "Çalıştırdığı hizmetçi yorgun argın yattı."}],
[["rc_condition_a", 111], "DashedAcceptabilityJudgment", {s: "Kovdukları sunucu olağanüstü bir hızla konuştular."}],
[["rc_condition_b", 111], "DashedAcceptabilityJudgment", {s: "Kovdukları sunucu olağanüstü bir hızla konuştu."}],
[["rc_condition_c", 111], "DashedAcceptabilityJudgment", {s: "Kovduğu sunucu olağanüstü bir hızla konuştular."}],
[["rc_condition_d", 111], "DashedAcceptabilityJudgment", {s: "Kovduğu sunucu olağanüstü bir hızla konuştu."}],
[["rc_condition_a", 112], "DashedAcceptabilityJudgment", {s: "Kaybettikleri turist aç susuz dolaştılar."}],
[["rc_condition_b", 112], "DashedAcceptabilityJudgment", {s: "Kaybettikleri turist aç susuz dolaştı."}],
[["rc_condition_c", 112], "DashedAcceptabilityJudgment", {s: "Kaybettiği turist aç susuz dolaştılar."}],
[["rc_condition_d", 112], "DashedAcceptabilityJudgment", {s: "Kaybettiği turist aç susuz dolaştı."}],
[["rc_condition_a", 113], "DashedAcceptabilityJudgment", {s: "Cezalandırdıkları hoca hapisten çabucak çıktılar."}],
[["rc_condition_b", 113], "DashedAcceptabilityJudgment", {s: "Cezalandırdıkları hoca hapisten çabucak çıktı."}],
[["rc_condition_c", 113], "DashedAcceptabilityJudgment", {s: "Cezalandırdığı hoca hapisten çabucak çıktılar."}],
[["rc_condition_d", 113], "DashedAcceptabilityJudgment", {s: "Cezalandırdığı hoca hapisten çabucak çıktı."}],
[["rc_condition_a", 114], "DashedAcceptabilityJudgment", {s: "Uyandırdıkları çaycı nedensiz yere kızdılar."}],
[["rc_condition_b", 114], "DashedAcceptabilityJudgment", {s: "Uyandırdıkları çaycı nedensiz yere kızdı."}],
[["rc_condition_c", 114], "DashedAcceptabilityJudgment", {s: "Uyandırdığı çaycı nedensiz yere kızdılar."}],
[["rc_condition_d", 114], "DashedAcceptabilityJudgment", {s: "Uyandırdığı çaycı nedensiz yere kızdı."}],
[["rc_condition_a", 115], "DashedAcceptabilityJudgment", {s: "Susturdukları hemşire etrafta amaçsızca gezdiler."}],
[["rc_condition_b", 115], "DashedAcceptabilityJudgment", {s: "Susturdukları hemşire etrafta amaçsızca gezdi."}],
[["rc_condition_c", 115], "DashedAcceptabilityJudgment", {s: "Susturduğu hemşire etrafta amaçsızca gezdiler."}],
[["rc_condition_d", 115], "DashedAcceptabilityJudgment", {s: "Susturduğu hemşire etrafta amaçsızca gezdi."}],
[["rc_condition_a", 116], "DashedAcceptabilityJudgment", {s: "Sordukları müdire biraz önce aradılar."}],
[["rc_condition_b", 116], "DashedAcceptabilityJudgment", {s: "Sordukları müdire biraz önce aradı."}],
[["rc_condition_c", 116], "DashedAcceptabilityJudgment", {s: "Sorduğu müdire biraz önce aradılar."}],
[["rc_condition_d", 116], "DashedAcceptabilityJudgment", {s: "Sorduğu müdire biraz önce aradı."}],
[["rc_condition_a", 117], "DashedAcceptabilityJudgment", {s: "Gönderdikleri terzi tamamen gereksizce bağırdılar."}],
[["rc_condition_b", 117], "DashedAcceptabilityJudgment", {s: "Gönderdikleri terzi tamamen gereksizce bağırdı."}],
[["rc_condition_c", 117], "DashedAcceptabilityJudgment", {s: "Gönderdiği terzi tamamen gereksizce bağırdılar."}],
[["rc_condition_d", 117], "DashedAcceptabilityJudgment", {s: "Gönderdiği terzi tamamen gereksizce bağırdı."}],
[["rc_condition_a", 118], "DashedAcceptabilityJudgment", {s: "Buldukları bakıcı çok kibar davrandılar."}],
[["rc_condition_b", 118], "DashedAcceptabilityJudgment", {s: "Buldukları bakıcı çok kibar davrandı."}],
[["rc_condition_c", 118], "DashedAcceptabilityJudgment", {s: "Bulduğu bakıcı çok kibar davrandılar."}],
[["rc_condition_d", 118], "DashedAcceptabilityJudgment", {s: "Bulduğu bakıcı çok kibar davrandı."}],
[["rc_condition_a", 119], "DashedAcceptabilityJudgment", {s: "Beğendikleri dadı sahil boyunca süzüldüler."}],
[["rc_condition_b", 119], "DashedAcceptabilityJudgment", {s: "Beğendikleri dadı sahil boyunca süzüldü."}],
[["rc_condition_c", 119], "DashedAcceptabilityJudgment", {s: "Beğendiği dadı sahil boyunca süzüldüler."}],
[["rc_condition_d", 119], "DashedAcceptabilityJudgment", {s: "Beğendiği dadı sahil boyunca süzüldü."}],
[["rc_condition_a", 120], "DashedAcceptabilityJudgment", {s: "Araştırdıkları tamirci çok yavaş çalıştılar."}],
[["rc_condition_b", 120], "DashedAcceptabilityJudgment", {s: "Araştırdıkları tamirci çok yavaş çalıştı."}],
[["rc_condition_c", 120], "DashedAcceptabilityJudgment", {s: "Araştırdığı tamirci çok yavaş çalıştılar."}],
[["rc_condition_d", 120], "DashedAcceptabilityJudgment", {s: "Araştırdığı tamirci çok yavaş çalıştı."}],
[["rc_condition_a", 121], "DashedAcceptabilityJudgment", {s: "Efkarlandırdıkları taksici saatlerce durmaksızın içtiler."}],
[["rc_condition_b", 121], "DashedAcceptabilityJudgment", {s: "Efkarlandırdıkları taksici saatlerce durmaksızın içti."}],
[["rc_condition_c", 121], "DashedAcceptabilityJudgment", {s: "Efkarlandırdığı taksici saatlerce durmaksızın içtiler."}],
[["rc_condition_d", 121], "DashedAcceptabilityJudgment", {s: "Efkarlandırdığı taksici saatlerce durmaksızın içti."}],
[["rc_condition_a", 122], "DashedAcceptabilityJudgment", {s: "Kovaladıkları çalgıcı feci bir şekilde öldüler."}],
[["rc_condition_b", 122], "DashedAcceptabilityJudgment", {s: "Kovaladıkları çalgıcı feci bir şekilde öldü."}],
[["rc_condition_c", 122], "DashedAcceptabilityJudgment", {s: "Kovaladığı çalgıcı feci bir şekilde öldüler."}],
[["rc_condition_d", 122], "DashedAcceptabilityJudgment", {s: "Kovaladığı çalgıcı feci bir şekilde öldü."}],
[["rc_condition_a", 123], "DashedAcceptabilityJudgment", {s: "Gittikleri dişçi ilk kez çılgınca eğlendiler."}],
[["rc_condition_b", 123], "DashedAcceptabilityJudgment", {s: "Gittikleri dişçi ilk kez çılgınca eğlendi."}],
[["rc_condition_c", 123], "DashedAcceptabilityJudgment", {s: "Gittiği dişçi ilk kez çılgınca eğlendiler."}],
[["rc_condition_d", 123], "DashedAcceptabilityJudgment", {s: "Gittiği dişçi ilk kez çılgınca eğlendi."}],
[["rc_condition_a", 124], "DashedAcceptabilityJudgment", {s: "Ağlattıkları müşteri şikayetinden hemen sonra sustular."}],
[["rc_condition_b", 124], "DashedAcceptabilityJudgment", {s: "Ağlattıkları müşteri şikayetinden hemen sonra sustu."}],
[["rc_condition_c", 124], "DashedAcceptabilityJudgment", {s: "Ağlattığı müşteri şikayetinden hemen sonra sustular."}],
[["rc_condition_d", 124], "DashedAcceptabilityJudgment", {s: "Ağlattığı müşteri şikayetinden hemen sonra sustu."}],
[["rc_condition_a", 125], "DashedAcceptabilityJudgment", {s: "Çıldırttıkları koruma her zamanki gibi geciktiler."}],
[["rc_condition_b", 125], "DashedAcceptabilityJudgment", {s: "Çıldırttıkları koruma her zamanki gibi gecikti."}],
[["rc_condition_c", 125], "DashedAcceptabilityJudgment", {s: "Çıldırttığı koruma her zamanki gibi geciktiler."}],
[["rc_condition_d", 125], "DashedAcceptabilityJudgment", {s: "Çıldırttığı koruma her zamanki gibi gecikti."}],
[["rc_condition_a", 126], "DashedAcceptabilityJudgment", {s: "Getirdikleri izleyici akşama kadar sessizce oturdular."}],
[["rc_condition_b", 126], "DashedAcceptabilityJudgment", {s: "Getirdikleri izleyici akşama kadar sessizce oturdu."}],
[["rc_condition_c", 126], "DashedAcceptabilityJudgment", {s: "Getirdiği izleyici akşama kadar sessizce oturdular."}],
[["rc_condition_d", 126], "DashedAcceptabilityJudgment", {s: "Getirdiği izleyici akşama kadar sessizce oturdu."}],
[["rc_condition_a", 127], "DashedAcceptabilityJudgment", {s: "Delirttikleri hasta akşamki muayeneden önce kaçtılar."}],
[["rc_condition_b", 127], "DashedAcceptabilityJudgment", {s: "Delirttikleri hasta akşamki muayeneden önce kaçtı."}],
[["rc_condition_c", 127], "DashedAcceptabilityJudgment", {s: "Delirttiği hasta akşamki muayeneden önce kaçtılar."}],
[["rc_condition_d", 127], "DashedAcceptabilityJudgment", {s: "Delirttiği hasta akşamki muayeneden önce kaçtı."}],
[["rc_condition_a", 128], "DashedAcceptabilityJudgment", {s: "Anlaştıkları terapist bile bile geç kaldılar."}],
[["rc_condition_b", 128], "DashedAcceptabilityJudgment", {s: "Anlaştıkları terapist bile bile geç kaldı."}],
[["rc_condition_c", 128], "DashedAcceptabilityJudgment", {s: "Anlaştığı terapist bile bile geç kaldılar."}],
[["rc_condition_d", 128], "DashedAcceptabilityJudgment", {s: "Anlaştığı terapist bile bile geç kaldı."}],
[["rc_condition_a", 129], "DashedAcceptabilityJudgment", {s: "Güvendikleri işçi beklenmedik bir anda hastalandılar."}],
[["rc_condition_b", 129], "DashedAcceptabilityJudgment", {s: "Güvendikleri işçi beklenmedik bir anda hastalandı."}],
[["rc_condition_c", 129], "DashedAcceptabilityJudgment", {s: "Güvendiği işçi beklenmedik bir anda hastalandılar."}],
[["rc_condition_d", 129], "DashedAcceptabilityJudgment", {s: "Güvendiği işçi beklenmedik bir anda hastalandı."}],
[["rc_condition_a", 130], "DashedAcceptabilityJudgment", {s: "Eğittikleri hostes sert rüzgarlardan dolayı üşüdüler."}],
[["rc_condition_b", 130], "DashedAcceptabilityJudgment", {s: "Eğittikleri hostes sert rüzgarlardan dolayı üşüdü."}],
[["rc_condition_c", 130], "DashedAcceptabilityJudgment", {s: "Eğittiği hostes sert rüzgarlardan dolayı üşüdüler."}],
[["rc_condition_d", 130], "DashedAcceptabilityJudgment", {s: "Eğittiği hostes sert rüzgarlardan dolayı üşüdü."}],
[["rc_condition_a", 131], "DashedAcceptabilityJudgment", {s: "Doyurdukları yolcu yemekten sonra yine acıktılar."}],
[["rc_condition_b", 131], "DashedAcceptabilityJudgment", {s: "Doyurdukları yolcu yemekten sonra yine acıktı."}],
[["rc_condition_c", 131], "DashedAcceptabilityJudgment", {s: "Doyurduğu yolcu yemekten sonra yine acıktılar."}],
[["rc_condition_d", 131], "DashedAcceptabilityJudgment", {s: "Doyurduğu yolcu yemekten sonra yine acıktı."}],
[["rc_condition_a", 132], "DashedAcceptabilityJudgment", {s: "Çağırdıkları kapıcı erken ödemeden dolayı sevindiler."}],
[["rc_condition_b", 132], "DashedAcceptabilityJudgment", {s: "Çağırdıkları kapıcı erken ödemeden dolayı sevindi."}],
[["rc_condition_c", 132], "DashedAcceptabilityJudgment", {s: "Çağırdığı kapıcı erken ödemeden dolayı sevindiler."}],
[["rc_condition_d", 132], "DashedAcceptabilityJudgment", {s: "Çağırdığı kapıcı erken ödemeden dolayı sevindi."}],
[["rc_condition_a", 133], "DashedAcceptabilityJudgment", {s: "Yordukları nakliyeci mesaiden hemen sonra uzandılar."}],
[["rc_condition_b", 133], "DashedAcceptabilityJudgment", {s: "Yordukları nakliyeci mesaiden hemen sonra uzandı."}],
[["rc_condition_c", 133], "DashedAcceptabilityJudgment", {s: "Yorduğu nakliyeci mesaiden hemen sonra uzandılar."}],
[["rc_condition_d", 133], "DashedAcceptabilityJudgment", {s: "Yorduğu nakliyeci mesaiden hemen sonra uzandı."}],
[["rc_condition_a", 134], "DashedAcceptabilityJudgment", {s: "Yetiştirdikleri eğitimci ilk denemede epey zorlandılar."}],
[["rc_condition_b", 134], "DashedAcceptabilityJudgment", {s: "Yetiştirdikleri eğitimci ilk denemede epey zorlandı."}],
[["rc_condition_c", 134], "DashedAcceptabilityJudgment", {s: "Yetiştirdiği eğitimci ilk denemede epey zorlandılar."}],
[["rc_condition_d", 134], "DashedAcceptabilityJudgment", {s: "Yetiştirdiği eğitimci ilk denemede epey zorlandı."}],
[["rc_condition_a", 135], "DashedAcceptabilityJudgment", {s: "Kiraladıkları animatör geç bir vakitte kalktılar."}],
[["rc_condition_b", 135], "DashedAcceptabilityJudgment", {s: "Kiraladıkları animatör geç bir vakitte kalktı."}],
[["rc_condition_c", 135], "DashedAcceptabilityJudgment", {s: "Kiraladığı animatör geç bir vakitte kalktılar."}],
[["rc_condition_d", 135], "DashedAcceptabilityJudgment", {s: "Kiraladığı animatör geç bir vakitte kalktı."}],
[["rc_condition_a", 136], "DashedAcceptabilityJudgment", {s: "Yaraladıkları polis müthiş bir ağrıyla uyandılar."}],
[["rc_condition_b", 136], "DashedAcceptabilityJudgment", {s: "Yaraladıkları polis müthiş bir ağrıyla uyandı."}],
[["rc_condition_c", 136], "DashedAcceptabilityJudgment", {s: "Yaraladığı polis müthiş bir ağrıyla uyandılar."}],
[["rc_condition_d", 136], "DashedAcceptabilityJudgment", {s: "Yaraladığı polis müthiş bir ağrıyla uyandı."}],
[["rc_condition_a", 137], "DashedAcceptabilityJudgment", {s: "Kaçırdıkları hırsız boş bir caddede yürüdüler."}],
[["rc_condition_b", 137], "DashedAcceptabilityJudgment", {s: "Kaçırdıkları hırsız boş bir caddede yürüdü."}],
[["rc_condition_c", 137], "DashedAcceptabilityJudgment", {s: "Kaçırdığı hırsız boş bir caddede yürüdüler."}],
[["rc_condition_d", 137], "DashedAcceptabilityJudgment", {s: "Kaçırdığı hırsız boş bir caddede yürüdü."}],
[["rc_condition_a", 138], "DashedAcceptabilityJudgment", {s: "Zehirledikleri kral toplantıdan sonra birden sarardılar."}],
[["rc_condition_b", 138], "DashedAcceptabilityJudgment", {s: "Zehirledikleri kral toplantıdan sonra birden sarardı."}],
[["rc_condition_c", 138], "DashedAcceptabilityJudgment", {s: "Zehirlediği kral toplantıdan sonra birden sarardılar."}],
[["rc_condition_d", 138], "DashedAcceptabilityJudgment", {s: "Zehirlediği kral toplantıdan sonra birden sarardı."}],
[["rc_condition_a", 139], "DashedAcceptabilityJudgment", {s: "Gezdirdikleri falcı yabancı bir ülkede kayboldular."}],
[["rc_condition_b", 139], "DashedAcceptabilityJudgment", {s: "Gezdirdikleri falcı yabancı bir ülkede kayboldu."}],
[["rc_condition_c", 139], "DashedAcceptabilityJudgment", {s: "Gezdirdiği falcı yabancı bir ülkede kayboldular."}],
[["rc_condition_d", 139], "DashedAcceptabilityJudgment", {s: "Gezdirdiği falcı yabancı bir ülkede kayboldu."}],
[["rc_condition_a", 140], "DashedAcceptabilityJudgment", {s: "Şüphelendirdikleri bekçi normalden çok yavaş gezindiler."}],
[["rc_condition_b", 140], "DashedAcceptabilityJudgment", {s: "Şüphelendirdikleri bekçi normalden çok yavaş gezindi."}],
[["rc_condition_c", 140], "DashedAcceptabilityJudgment", {s: "Şüphelendirdiği bekçi normalden çok yavaş gezindiler."}],
[["rc_condition_d", 140], "DashedAcceptabilityJudgment", {s: "Şüphelendirdiği bekçi normalden çok yavaş gezindi."}],

[["gen_condition_c", 1], "DashedAcceptabilityJudgment", {s: "Yöneticilerin aşçısı mutfakta sürekli zıpladılar."  } ],
[["gen_condition_c", 1], "DashedAcceptabilityJudgment", {s: "Yöneticilerin aşçısı mutfakta sürekli zıpladı."  } ],
[["gen_condition_c", 1], "DashedAcceptabilityJudgment", {s: "Yöneticinin aşçısı mutfakta sürekli zıpladılar."  } ],
[["gen_condition_c", 1], "DashedAcceptabilityJudgment", {s: "Yöneticinin aşçısı mutfakta sürekli zıpladı."  } ],
[["gen_condition_c", 2], "DashedAcceptabilityJudgment", {s: "Öğrencilerin ablası sınıfta birden bayıldılar."  } ],
[["gen_condition_c", 2], "DashedAcceptabilityJudgment", {s: "Öğrencilerin ablası sınıfta birden bayıldı."  } ],
[["gen_condition_c", 2], "DashedAcceptabilityJudgment", {s: "Öğrencinin ablası sınıfta birden bayıldılar."  } ],
[["gen_condition_c", 2], "DashedAcceptabilityJudgment", {s: "Öğrencinin ablası sınıfta birden bayıldı."  } ],
[["gen_condition_c", 3], "DashedAcceptabilityJudgment", {s: "Marangozların abisi atölyeden hızla uzaklaştılar."  } ],
[["gen_condition_c", 3], "DashedAcceptabilityJudgment", {s: "Marangozların abisi atölyeden hızla uzaklaştı."  } ],
[["gen_condition_c", 3], "DashedAcceptabilityJudgment", {s: "Marangozun abisi atölyeden hızla uzaklaştılar."  } ],
[["gen_condition_c", 3], "DashedAcceptabilityJudgment", {s: "Marangozun abisi atölyeden hızla uzaklaştı."  } ],
[["gen_condition_c", 4], "DashedAcceptabilityJudgment", {s: "Mahallelilerin emlakçısı aniden küstahça güldüler."  } ],
[["gen_condition_c", 4], "DashedAcceptabilityJudgment", {s: "Mahallelilerin emlakçısı aniden küstahça güldü."  } ],
[["gen_condition_c", 4], "DashedAcceptabilityJudgment", {s: "Mahallelinin emlakçısı aniden küstahça güldüler."  } ],
[["gen_condition_c", 4], "DashedAcceptabilityJudgment", {s: "Mahallelinin emlakçısı aniden küstahça güldü."  } ],
[["gen_condition_c", 5], "DashedAcceptabilityJudgment", {s: "Kızların halası sabaha olana kadar ağladılar."  } ],
[["gen_condition_c", 5], "DashedAcceptabilityJudgment", {s: "Kızların halası sabaha olana kadar ağladı."  } ],
[["gen_condition_c", 5], "DashedAcceptabilityJudgment", {s: "Kızın halası sabaha olana kadar ağladılar."  } ],
[["gen_condition_c", 5], "DashedAcceptabilityJudgment", {s: "Kızın halası sabaha olana kadar ağladı."  } ],
[["gen_condition_c", 6], "DashedAcceptabilityJudgment", {s: "Damatların dayısı arada sırada sıkıldılar."  } ],
[["gen_condition_c", 6], "DashedAcceptabilityJudgment", {s: "Damatların dayısı arada sırada sıkıldı."  } ],
[["gen_condition_c", 6], "DashedAcceptabilityJudgment", {s: "Damatın dayısı arada sırada sıkıldılar."  } ],
[["gen_condition_c", 6], "DashedAcceptabilityJudgment", {s: "Damatın dayısı arada sırada sıkıldı."  } ],
[["gen_condition_c", 7], "DashedAcceptabilityJudgment", {s: "Doktorların çiçekçisi günden güne durmadan zayıfladılar."  } ],
[["gen_condition_c", 7], "DashedAcceptabilityJudgment", {s: "Doktorların çiçekçisi günden güne durmadan zayıfladı."  } ],
[["gen_condition_c", 7], "DashedAcceptabilityJudgment", {s: "Doktorun çiçekçisi günden güne durmadan zayıfladılar."  } ],
[["gen_condition_c", 7], "DashedAcceptabilityJudgment", {s: "Doktorun çiçekçisi günden güne durmadan zayıfladı."  } ],
[["gen_condition_c", 8], "DashedAcceptabilityJudgment", {s: "Stajyerlerin eniştesi gece ikiden önce uyudular."  } ],
[["gen_condition_c", 8], "DashedAcceptabilityJudgment", {s: "Stajyerlerin eniştesi gece ikiden önce uyudu."  } ],
[["gen_condition_c", 8], "DashedAcceptabilityJudgment", {s: "Stajyerin eniştesi gece ikiden önce uyudular."  } ],
[["gen_condition_c", 8], "DashedAcceptabilityJudgment", {s: "Stajyerin eniştesi gece ikiden önce uyudu."  } ],
[["gen_condition_c", 9], "DashedAcceptabilityJudgment", {s: "Aristokratların hizmetçisi yorgun argın yattılar."  } ],
[["gen_condition_c", 9], "DashedAcceptabilityJudgment", {s: "Aristokratların hizmetçisi yorgun argın yattı."  } ],
[["gen_condition_c", 9], "DashedAcceptabilityJudgment", {s: "Aristokratın hizmetçisi yorgun argın yattılar."  } ],
[["gen_condition_c", 9], "DashedAcceptabilityJudgment", {s: "Aristokratın hizmetçisi yorgun argın yattı."  } ],
[["gen_condition_c", 10], "DashedAcceptabilityJudgment", {s: "Konuşmacıların sunucusu olağanüstü bir hızla koştular."  } ],
[["gen_condition_c", 10], "DashedAcceptabilityJudgment", {s: "Konuşmacıların sunucusu olağanüstü bir hızla koştu."  } ],
[["gen_condition_c", 10], "DashedAcceptabilityJudgment", {s: "Konuşmacının sunucusu olağanüstü bir hızla koştular."  } ],
[["gen_condition_c", 10], "DashedAcceptabilityJudgment", {s: "Konuşmacının sunucusu olağanüstü bir hızla koştu."  } ],
[["gen_condition_c", 11], "DashedAcceptabilityJudgment", {s: "Psikiyatristlerin eczacısı aç susuz çalıştılar."  } ],
[["gen_condition_c", 11], "DashedAcceptabilityJudgment", {s: "Psikiyatristlerin eczacısı aç susuz çalıştı."  } ],
[["gen_condition_c", 11], "DashedAcceptabilityJudgment", {s: "Psikiyatristin eczacısı aç susuz çalıştılar."  } ],
[["gen_condition_c", 11], "DashedAcceptabilityJudgment", {s: "Psikiyatristin eczacısı aç susuz çalıştı."  } ],
[["gen_condition_c", 12], "DashedAcceptabilityJudgment", {s: "Politikacıların hocası adliyeden çabucak çıktılar."  } ],
[["gen_condition_c", 12], "DashedAcceptabilityJudgment", {s: "Politikacıların hocası adliyeden çabucak çıktı."  } ],
[["gen_condition_c", 12], "DashedAcceptabilityJudgment", {s: "Politikacının hocası adliyeden çabucak çıktılar."  } ],
[["gen_condition_c", 12], "DashedAcceptabilityJudgment", {s: "Politikacının hocası adliyeden çabucak çıktı."  } ],
[["gen_condition_c", 13], "DashedAcceptabilityJudgment", {s: "Hakimlerin çaycısı nedensiz yere kızdılar."  } ],
[["gen_condition_c", 13], "DashedAcceptabilityJudgment", {s: "Hakimlerin çaycısı nedensiz yere kızdı."  } ],
[["gen_condition_c", 13], "DashedAcceptabilityJudgment", {s: "Hakimin çaycısı nedensiz yere kızdılar."  } ],
[["gen_condition_c", 13], "DashedAcceptabilityJudgment", {s: "Hakimin çaycısı nedensiz yere kızdı."  } ],
[["gen_condition_c", 14], "DashedAcceptabilityJudgment", {s: "Oyuncuların hemşiresi etrafta amaçsızca gezdiler."  } ],
[["gen_condition_c", 14], "DashedAcceptabilityJudgment", {s: "Oyuncuların hemşiresi etrafta amaçsızca gezdi."  } ],
[["gen_condition_c", 14], "DashedAcceptabilityJudgment", {s: "Oyuncunun hemşiresi etrafta amaçsızca gezdiler."  } ],
[["gen_condition_c", 14], "DashedAcceptabilityJudgment", {s: "Oyuncunun hemşiresi etrafta amaçsızca gezdi."  } ],
[["gen_condition_c", 15], "DashedAcceptabilityJudgment", {s: "Öğretmenlerin müdiresi biraz önce aradılar."  } ],
[["gen_condition_c", 15], "DashedAcceptabilityJudgment", {s: "Öğretmenlerin müdiresi biraz önce aradı."  } ],
[["gen_condition_c", 15], "DashedAcceptabilityJudgment", {s: "Öğretmenin müdiresi biraz önce aradılar."  } ],
[["gen_condition_c", 15], "DashedAcceptabilityJudgment", {s: "Öğretmenin müdiresi biraz önce aradı."  } ],
[["gen_condition_c", 16], "DashedAcceptabilityJudgment", {s: "Milyonerlerin terzisi tamamen gereksizce kovuldular."  } ],
[["gen_condition_c", 16], "DashedAcceptabilityJudgment", {s: "Milyonerlerin terzisi tamamen gereksizce kovuldu."  } ],
[["gen_condition_c", 16], "DashedAcceptabilityJudgment", {s: "Milyonerin terzisi tamamen gereksizce kovuldular."  } ],
[["gen_condition_c", 16], "DashedAcceptabilityJudgment", {s: "Milyonerin terzisi tamamen gereksizce kovuldu."  } ],
[["gen_condition_c", 17], "DashedAcceptabilityJudgment", {s: "Bebeklerin bakıcısı çok kibar davrandılar."  } ],
[["gen_condition_c", 17], "DashedAcceptabilityJudgment", {s: "Bebeklerin bakıcısı çok kibar davrandı."  } ],
[["gen_condition_c", 17], "DashedAcceptabilityJudgment", {s: "Bebeğin bakıcısı çok kibar davrandılar."  } ],
[["gen_condition_c", 17], "DashedAcceptabilityJudgment", {s: "Bebeğin bakıcısı çok kibar davrandı."  } ],
[["gen_condition_c", 18], "DashedAcceptabilityJudgment", {s: "Çocukların dadısı yüksek sesle konuştular."  } ],
[["gen_condition_c", 18], "DashedAcceptabilityJudgment", {s: "Çocukların dadısı yüksek sesle konuştu."  } ],
[["gen_condition_c", 18], "DashedAcceptabilityJudgment", {s: "Çocuğun dadısı yüksek sesle konuştular."  } ],
[["gen_condition_c", 18], "DashedAcceptabilityJudgment", {s: "Çocuğun dadısı yüksek sesle konuştu."  } ],
[["gen_condition_c", 19], "DashedAcceptabilityJudgment", {s: "Futbolcuların sürücüsü çok yavaş ilerlediler."  } ],
[["gen_condition_c", 19], "DashedAcceptabilityJudgment", {s: "Futbolcuların sürücüsü çok yavaş ilerledi."  } ],
[["gen_condition_c", 19], "DashedAcceptabilityJudgment", {s: "Futbolcunun sürücüsü çok yavaş ilerlediler."  } ],
[["gen_condition_c", 19], "DashedAcceptabilityJudgment", {s: "Futbolcunun sürücüsü çok yavaş ilerledi."  } ],
[["gen_condition_c", 20], "DashedAcceptabilityJudgment", {s: "Modacıların taksicisi saatlerce durmaksızın içtiler."  } ],
[["gen_condition_c", 20], "DashedAcceptabilityJudgment", {s: "Modacıların taksicisi saatlerce durmaksızın içti."  } ],
[["gen_condition_c", 20], "DashedAcceptabilityJudgment", {s: "Modacının taksicisi saatlerce durmaksızın içtiler."  } ],
[["gen_condition_c", 20], "DashedAcceptabilityJudgment", {s: "Modacının taksicisi saatlerce durmaksızın içti."  } ],
[["gen_condition_c", 21], "DashedAcceptabilityJudgment", {s: "Sanatçıların çalgıcısı feci bir şekilde öldüler."  } ],
[["gen_condition_c", 21], "DashedAcceptabilityJudgment", {s: "Sanatçıların çalgıcısı feci bir şekilde öldü."  } ],
[["gen_condition_c", 21], "DashedAcceptabilityJudgment", {s: "Sanatçının çalgıcısı feci bir şekilde öldüler."  } ],
[["gen_condition_c", 21], "DashedAcceptabilityJudgment", {s: "Sanatçının çalgıcısı feci bir şekilde öldü."  } ],
[["gen_condition_c", 22], "DashedAcceptabilityJudgment", {s: "Dedektiflerin dişçisi ilk kez çılgınca eğlendiler."  } ],
[["gen_condition_c", 22], "DashedAcceptabilityJudgment", {s: "Dedektiflerin dişçisi ilk kez çılgınca eğlendi."  } ],
[["gen_condition_c", 22], "DashedAcceptabilityJudgment", {s: "Dedektifin dişçisi ilk kez çılgınca eğlendiler."  } ],
[["gen_condition_c", 22], "DashedAcceptabilityJudgment", {s: "Dedektifin dişçisi ilk kez çılgınca eğlendi."  } ],
[["gen_condition_c", 23], "DashedAcceptabilityJudgment", {s: "Esnafların müşterisi şikayettten hemen sonra sustular."  } ],
[["gen_condition_c", 23], "DashedAcceptabilityJudgment", {s: "Esnafların müşterisi şikayettten hemen sonra sustu."  } ],
[["gen_condition_c", 23], "DashedAcceptabilityJudgment", {s: "Esnafın müşterisi şikayettten hemen sonra sustular."  } ],
[["gen_condition_c", 23], "DashedAcceptabilityJudgment", {s: "Esnafın müşterisi şikayettten hemen sonra sustu."  } ],
[["gen_condition_c", 24], "DashedAcceptabilityJudgment", {s: "Şarkıcıların koruması her zamanki gibi geciktiler."  } ],
[["gen_condition_c", 24], "DashedAcceptabilityJudgment", {s: "Şarkıcıların koruması her zamanki gibi gecikti."  } ],
[["gen_condition_c", 24], "DashedAcceptabilityJudgment", {s: "Şarkıcının koruması her zamanki gibi geciktiler."  } ],
[["gen_condition_c", 24], "DashedAcceptabilityJudgment", {s: "Şarkıcının koruması her zamanki gibi gecikti."  } ],
[["gen_condition_c", 25], "DashedAcceptabilityJudgment", {s: "Göstericilerin izleyicisi akşama kadar sessizce oturdular."  } ],
[["gen_condition_c", 25], "DashedAcceptabilityJudgment", {s: "Göstericilerin izleyicisi akşama kadar sessizce oturdu."  } ],
[["gen_condition_c", 25], "DashedAcceptabilityJudgment", {s: "Göstericinin izleyicisi akşama kadar sessizce oturdular."  } ],
[["gen_condition_c", 25], "DashedAcceptabilityJudgment", {s: "Göstericinin izleyicisi akşama kadar sessizce oturdu."  } ],
[["gen_condition_c", 26], "DashedAcceptabilityJudgment", {s: "Cerrahların hastası akşamki gösteriden önce kaçtılar."  } ],
[["gen_condition_c", 26], "DashedAcceptabilityJudgment", {s: "Cerrahların hastası akşamki gösteriden önce kaçtı."  } ],
[["gen_condition_c", 26], "DashedAcceptabilityJudgment", {s: "Cerrahın hastası akşamki gösteriden önce kaçtılar."  } ],
[["gen_condition_c", 26], "DashedAcceptabilityJudgment", {s: "Cerrahın hastası akşamki gösteriden önce kaçtı."  } ],
[["gen_condition_c", 27], "DashedAcceptabilityJudgment", {s: "Dalgıçların eğitimcisi bile bile geç kaldılar."  } ],
[["gen_condition_c", 27], "DashedAcceptabilityJudgment", {s: "Dalgıçların eğitimcisi bile bile geç kaldı."  } ],
[["gen_condition_c", 27], "DashedAcceptabilityJudgment", {s: "Dalgıcın eğitimcisi bile bile geç kaldılar."  } ],
[["gen_condition_c", 27], "DashedAcceptabilityJudgment", {s: "Dalgıcın eğitimcisi bile bile geç kaldı."  } ],
[["gen_condition_c", 28], "DashedAcceptabilityJudgment", {s: "Fabrikatörlerin işçisi beklenmedik bir anda hastalandılar."  } ],
[["gen_condition_c", 28], "DashedAcceptabilityJudgment", {s: "Fabrikatörlerin işçisi beklenmedik bir anda hastalandı."  } ],
[["gen_condition_c", 28], "DashedAcceptabilityJudgment", {s: "Fabrikatörün işçisi beklenmedik bir anda hastalandılar."  } ],
[["gen_condition_c", 28], "DashedAcceptabilityJudgment", {s: "Fabrikatörün işçisi beklenmedik bir anda hastalandı."  } ],
[["gen_condition_c", 29], "DashedAcceptabilityJudgment", {s: "Komedyenlerin yardımcısı poyrazdan dolayı üşüdüler."  } ],
[["gen_condition_c", 29], "DashedAcceptabilityJudgment", {s: "Komedyenlerin yardımcısı poyrazdan dolayı üşüdü."  } ],
[["gen_condition_c", 29], "DashedAcceptabilityJudgment", {s: "Komedyenin yardımcısı poyrazdan dolayı üşüdüler."  } ],
[["gen_condition_c", 29], "DashedAcceptabilityJudgment", {s: "Komedyenin yardımcısı poyrazdan dolayı üşüdü."  } ],
[["gen_condition_c", 30], "DashedAcceptabilityJudgment", {s: "Şoförlerin yolcusu yemekten sonra yine acıktılar."  } ],
[["gen_condition_c", 30], "DashedAcceptabilityJudgment", {s: "Şoförlerin yolcusu yemekten sonra yine acıktı."  } ],
[["gen_condition_c", 30], "DashedAcceptabilityJudgment", {s: "Şoförün yolcusu yemekten sonra yine acıktılar."  } ],
[["gen_condition_c", 30], "DashedAcceptabilityJudgment", {s: "Şoförün yolcusu yemekten sonra yine acıktı."  } ],
[["gen_condition_c", 31], "DashedAcceptabilityJudgment", {s: "Mühendislerin kapıcısı erken ödemeden dolayı sevindiler."  } ],
[["gen_condition_c", 31], "DashedAcceptabilityJudgment", {s: "Mühendislerin kapıcısı erken ödemeden dolayı sevindi."  } ],
[["gen_condition_c", 31], "DashedAcceptabilityJudgment", {s: "Mühendisin kapıcısı erken ödemeden dolayı sevindiler."  } ],
[["gen_condition_c", 31], "DashedAcceptabilityJudgment", {s: "Mühendisin kapıcısı erken ödemeden dolayı sevindi."  } ],
[["gen_condition_c", 32], "DashedAcceptabilityJudgment", {s: "Pazarcıların nakliyecisi mesaiden hemen sonra uzandılar."  } ],
[["gen_condition_c", 32], "DashedAcceptabilityJudgment", {s: "Pazarcıların nakliyecisi mesaiden hemen sonra uzandı."  } ],
[["gen_condition_c", 32], "DashedAcceptabilityJudgment", {s: "Pazarcının nakliyecisi mesaiden hemen sonra uzandılar."  } ],
[["gen_condition_c", 32], "DashedAcceptabilityJudgment", {s: "Pazarcının nakliyecisi mesaiden hemen sonra uzandı."  } ],
[["gen_condition_c", 33], "DashedAcceptabilityJudgment", {s: "Oyuncuların eğitimcisi ilk denemede epey zorlandılar."  } ],
[["gen_condition_c", 33], "DashedAcceptabilityJudgment", {s: "Oyuncuların eğitimcisi ilk denemede epey zorlandı."  } ],
[["gen_condition_c", 33], "DashedAcceptabilityJudgment", {s: "Oyuncunun eğitimcisi ilk denemede epey zorlandılar."  } ],
[["gen_condition_c", 33], "DashedAcceptabilityJudgment", {s: "Oyuncunun eğitimcisi ilk denemede epey zorlandı."  } ],
[["gen_condition_c", 34], "DashedAcceptabilityJudgment", {s: "Mankenlerin modacısı geç bir vakitte kalktılar."  } ],
[["gen_condition_c", 34], "DashedAcceptabilityJudgment", {s: "Mankenlerin modacısı geç bir vakitte kalktı."  } ],
[["gen_condition_c", 34], "DashedAcceptabilityJudgment", {s: "Mankenin modacısı geç bir vakitte kalktılar."  } ],
[["gen_condition_c", 34], "DashedAcceptabilityJudgment", {s: "Mankenin modacısı geç bir vakitte kalktı."  } ],
[["gen_condition_c", 35], "DashedAcceptabilityJudgment", {s: "Konukların teyzesi müthiş bir ağrıyla uyandılar."  } ],
[["gen_condition_c", 35], "DashedAcceptabilityJudgment", {s: "Konukların teyzesi müthiş bir ağrıyla uyandı."  } ],
[["gen_condition_c", 35], "DashedAcceptabilityJudgment", {s: "Konuğun teyzesi müthiş bir ağrıyla uyandılar."  } ],
[["gen_condition_c", 35], "DashedAcceptabilityJudgment", {s: "Konuğun teyzesi müthiş bir ağrıyla uyandı."  } ],
[["gen_condition_c", 36], "DashedAcceptabilityJudgment", {s: "Oğlanların amcası boş bir caddede yürüdüler."  } ],
[["gen_condition_c", 36], "DashedAcceptabilityJudgment", {s: "Oğlanların amcası boş bir caddede yürüdü."  } ],
[["gen_condition_c", 36], "DashedAcceptabilityJudgment", {s: "Oğlanın amcası boş bir caddede yürüdüler."  } ],
[["gen_condition_c", 36], "DashedAcceptabilityJudgment", {s: "Oğlanın amcası boş bir caddede yürüdü."  } ],
[["gen_condition_c", 37], "DashedAcceptabilityJudgment", {s: "Avukatların komşusu toplantıdan sonra birden sarardılar."  } ],
[["gen_condition_c", 37], "DashedAcceptabilityJudgment", {s: "Avukatların komşusu toplantıdan sonra birden sarardı."  } ],
[["gen_condition_c", 37], "DashedAcceptabilityJudgment", {s: "Avukatın komşusu toplantıdan sonra birden sarardılar."  } ],
[["gen_condition_c", 37], "DashedAcceptabilityJudgment", {s: "Avukatın komşusu toplantıdan sonra birden sarardı."  } ],
[["gen_condition_c", 38], "DashedAcceptabilityJudgment", {s: "Ünlülerin falcısı yabancı bir ülkede kayboldular."  } ],
[["gen_condition_c", 38], "DashedAcceptabilityJudgment", {s: "Ünlülerin falcısı yabancı bir ülkede kayboldu."  } ],
[["gen_condition_c", 38], "DashedAcceptabilityJudgment", {s: "Ünlünün falcısı yabancı bir ülkede kayboldular."  } ],
[["gen_condition_c", 38], "DashedAcceptabilityJudgment", {s: "Ünlünün falcısı yabancı bir ülkede kayboldu."  } ],
[["gen_condition_c", 39], "DashedAcceptabilityJudgment", {s: "Çiftçilerin bekçisi normalden çok yavaş gezindiler."  } ],
[["gen_condition_c", 39], "DashedAcceptabilityJudgment", {s: "Çiftçilerin bekçisi normalden çok yavaş gezindi."  } ],
[["gen_condition_c", 39], "DashedAcceptabilityJudgment", {s: "Çiftçinin bekçisi normalden çok yavaş gezindiler."  } ],
[["gen_condition_c", 39], "DashedAcceptabilityJudgment", {s: "Çiftçinin bekçisi normalden çok yavaş gezindi."  } ],
[["gen_condition_c", 40], "DashedAcceptabilityJudgment", {s: "Kadınların ninesi geçen seneye göre dinçleştiler."  } ],
[["gen_condition_c", 40], "DashedAcceptabilityJudgment", {s: "Kadınların ninesi geçen seneye göre dinçleşti."  } ],
[["gen_condition_c", 40], "DashedAcceptabilityJudgment", {s: "Kadının ninesi geçen seneye göre dinçleştiler."  } ],
[["gen_condition_c", 40], "DashedAcceptabilityJudgment", {s: "Kadının ninesi geçen seneye göre dinçleşti."  } ]



];